import PropTypes from 'prop-types';

export const leftPanelConfigPropType = PropTypes.arrayOf(
  PropTypes.shape({
    elements: PropTypes.arrayOf(
      PropTypes.shape({
        itemType: PropTypes.string,
        title: PropTypes.string,
      }),
    ),
    title: PropTypes.string,
  }),
);

export const iconSetConfigPropType = PropTypes.shape({
  CHART_SETTINGS: PropTypes.shape({
    bar: PropTypes.node,
    basic: PropTypes.node,
    column: PropTypes.node,
    donut: PropTypes.node,
    grid: PropTypes.node,
    heartRating: PropTypes.node,
    layout: PropTypes.node,
    line: PropTypes.node,
    pie: PropTypes.node,
    starRating: PropTypes.node,
    textGrid: PropTypes.node,
  }),
  CONTEXT_MENU: PropTypes.shape({
    moveToBack: PropTypes.node,
    moveToBackward: PropTypes.node,
    moveToForward: PropTypes.node,
    moveToFront: PropTypes.node,
  }),
  ELEMENT_MENU: PropTypes.shape({
    duplicate: PropTypes.node,
    settings: PropTypes.node,
  }),
  ELEMENTS: PropTypes.shape({
    email: PropTypes.node,
    header: PropTypes.node,
    icon: PropTypes.node,
    image: PropTypes.node,
    label: PropTypes.node,
    lock: PropTypes.node,
    multipleChoice: PropTypes.node,
    shapes: PropTypes.node,
    singleChoice: PropTypes.node,
    star: PropTypes.node,
    table: PropTypes.node,
    text: PropTypes.node,
    textElement: PropTypes.node,
    unlock: PropTypes.node,
  }),
  GENERAL: PropTypes.shape({
    allSlides: PropTypes.node,
    close: PropTypes.node,
    customize: PropTypes.node,
    down: PropTypes.node,
    drag: PropTypes.node,
    rotate: PropTypes.node,
    settingsToggle: PropTypes.node,
    slides: PropTypes.node,
    trash: PropTypes.node,
  }),
  LOADING: PropTypes.shape({
    loadingCircle: PropTypes.node,
  }),
  PAGE_MENU: PropTypes.shape({
    arrowDown: PropTypes.node,
    arrowLeft: PropTypes.node,
    arrowRight: PropTypes.node,
    arrowUp: PropTypes.node,
    duplicateLine: PropTypes.node,
    minus: PropTypes.node,
    pageSettings: PropTypes.node,
    plus: PropTypes.node,
    trashLine: PropTypes.node,
  }),
  PASSWORD_MODAL: PropTypes.shape({
    eye: PropTypes.node,
    key: PropTypes.node,
  }),
  PLACEHOLDER: PropTypes.shape({
    barPlaceholder: PropTypes.node,
    basicPlaceholder: PropTypes.node,
    columnPlaceholder: PropTypes.node,
    donutPlaceholder: PropTypes.node,
    linePlaceholder: PropTypes.node,
    piePlaceholder: PropTypes.node,
    textGridPlaceholder: PropTypes.node,
  }),
  PRESENTATION: PropTypes.shape({
    attachment: PropTypes.node,
    download: PropTypes.node,
    enterFullscreen: PropTypes.node,
    exitFullscreen: PropTypes.node,
    pause: PropTypes.node,
    pen: PropTypes.node,
    play: PropTypes.node,
    print: PropTypes.node,
    share: PropTypes.node,
  }),
  SETTINGS: PropTypes.shape({
    alignCenter: PropTypes.node,
    alignLeft: PropTypes.node,
    alignRight: PropTypes.node,
    bold: PropTypes.node,
    italic: PropTypes.node,
    underline: PropTypes.node,
  }),
  SHAPE_SETTINGS: PropTypes.shape({
    ellipseIcon: PropTypes.node,
    lineIcon: PropTypes.node,
    rectangleIcon: PropTypes.node,
    starIcon: PropTypes.node,
    triangleIcon: PropTypes.node,
  }),
  ZOOM: PropTypes.shape({
    fit: PropTypes.node,
  }),
});
