/* eslint-disable max-len */
export default [
  {
    id: '72m4j4',
    items: [
      {
        height: 794,
        id: '745o4o',
        itemType: 'shapes',
        left: 0,
        lineDirection: 'horizontal',
        lineSize: 'thin',
        lineType: 'solid',
        opacity: 1,
        pageID: '72m4j4',
        roundedCorners: 0,
        shapeFillColor: '#0C6DD5',
        shapeType: 'rectangle',
        top: 0,
        width: 1123,
      },
      {
        height: 184,
        id: '42539m',
        itemType: 'shapes',
        left: 0,
        lineDirection: 'horizontal',
        lineSize: 'thin',
        lineType: 'solid',
        opacity: 0.2,
        pageID: '72m4j4',
        roundedCorners: 0,
        shapeFillColor: 'rgba(0, 0, 0, 1)',
        shapeType: 'rectangle',
        top: 305,
        width: 1123,
      },
      {
        fontColor: '#FFFFFF',
        fontFamily: 'Roboto',
        fontSize: 64,
        fontStyle: '["bold"]',
        height: 104,
        id: 'ro0203',
        itemType: 'text',
        left: 0,
        opacity: 1,
        pageID: '72m4j4',
        textAlign: 'center',
        top: 360,
        value: '<center><p><strong style="font-size: 48px;">JOTFORM DND-BUILDER</strong></p></center>',
        width: 1123,
      },
    ],
    order: 1,
  },
  {
    id: '018r03',
    items: [
      {
        height: 56,
        id: '96o85m',
        itemType: 'shapes',
        left: 0,
        lineDirection: 'horizontal',
        lineSize: 'thin',
        lineType: 'solid',
        opacity: 1,
        pageID: '018r03',
        roundedCorners: 0,
        shapeFillColor: '#0c6dd5',
        shapeType: 'rectangle',
        top: 0,
        width: 1123,
      },
      {
        fontColor: '#FFFFFF',
        fontFamily: 'Roboto',
        fontSize: 24,
        fontStyle: '["bold"]',
        height: 38,
        id: '4jt0oo',
        itemType: 'text',
        left: 10,
        opacity: 1,
        pageID: '018r03',
        textAlign: 'left',
        top: 9,
        value: '<center><p><strong style="font-size: 24px;">Second Page</strong></p></center>',
        width: 1123,
      },
      {
        height: 589,
        id: 'jr4647',
        itemType: 'image',
        left: 267,
        opacity: 1,
        pageID: '018r03',
        top: 103,
        url: 'https://www.jotform.com/resources/assets/icon/jotform-logomark-transparent-400x400.png',
        width: 589,
      },
    ],
    order: 2,
  },
];
