name: Build and Test
on:
  # manual trigger
  workflow_dispatch:
  # reuse workflow run
  workflow_call:
  # on pull request
  pull_request:
  # on push to master branch
  push:
    branches:
      - 'master'
      - 'responsive-preview'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v4
          with:
            version: 11.5.0
        - uses: actions/setup-node@v3
          with:
            node-version-file: '.nvmrc'
            registry-url: https://registry.npmjs.org/
            cache: pnpm

        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        - name: Run linter
          run: pnpm lint

        - name: Build package
          run: pnpm build

        - name: Run tests
          run: pnpm test
