name: Publish
on:
  # on release
  release:
    types: [released, prereleased]

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
  publish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Publish package
        if: github.event_name == 'release' && github.event.release.draft == false
        run: |
          if [[ ${{ github.event.release.prerelease }} == true || ${{ github.event.release.tag_name }} =~ -alpha|-beta|-rc ]]; then
            pnpm publish --tag next
          else
            pnpm publish --tag latest
          fi

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BUILD_TOKEN }}
